### ISSUE TITLE
请问程序里面的数据集在哪下载呢parser.add_argument(  '--data-path', default='/paddle/data/ILSVRC2012_torch', help='dataset')

### ISSUE THREAD

**Issue by AI-Mart** [littletomatodonkey/AlexNet-Prod#1]
parser.add_argument(
        '--data-path', default='/paddle/data/ILSVRC2012_torch', help='dataset')

想本地把程序跑起来作比对

**Comment by littletomatodonkey** [comment]
你好，可以在从这里下载哈

https://github.com/pytorch/examples/tree/master/imagenet

**Comment by AI-Mart** [comment]
好的，谢谢老师

**Comment by livingbody** [comment]
> 好的，谢谢老师

巨大无比
