### ISSUE TITLE
该项目环境中torch和paddlepaddle等版本是多少？

### ISSUE THREAD

**Issue by livingbody** [littletomatodonkey/AlexNet-Prod#4]
亲，能提供下requirements.txt嘛？
我运行老出问题。

**Comment by livingbody** [comment]
weight = torch_dict[key].cpu().numpy()
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

**Comment by littletomatodonkey** [comment]
你好，我使用的torch是1.9.0，paddle是2.1.2哈，按照需要安装cpu或者gpu版本的即可
