### ISSUE TITLE
论文复现：from apex import amp出错

### ISSUE THREAD

**Issue by kjf4096** [littletomatodonkey/AlexNet-Prod#5]
在 AlexNet-paddle / train.py中有语句from apex import amp
但在aistudio中运行代码：
from apex import amp会出错。

应该怎么用paddle复现：
from apex import amp ？

**Comment by littletomatodonkey** [comment]
你好，这个是混合精度训练，目前paddle没有支持对apex库的支持，如果希望使用混合精度，可以参考：https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.2/ppcls/configs/ImageNet/ResNet/ResNet50_fp16_dygraph.yaml

**Comment by livingbody** [comment]
好嘞
