### ISSUE TITLE
requirement.txt 文件存在错误

### ISSUE THREAD

**Issue by lazyn1997** [littletomatodonkey/AlexNet-Prod#7]
requirement.txt 文件中第九行多打了个 ？，
![image](https://user-images.githubusercontent.com/34644177/135377561-018945ac-4be7-4e73-a45f-2e144e239a43.png)

导致安装 requirements 时报错，如下图所示，
![image](https://user-images.githubusercontent.com/34644177/135377587-7fc4a1e9-f591-4a05-b4d8-b63b1f5a4589.png)
删除后可顺利安装 requirement 
![image](https://user-images.githubusercontent.com/34644177/135377665-0b2fb1f1-7f59-4d68-9e40-142a55b4a63c.png)

**Comment by littletomatodonkey** [comment]
你好，感谢反馈，已修复~

**Comment by lazyn1997** [comment]
好的
