### ISSUE TITLE
无法保存比对结果

### ISSUE THREAD

**Issue by lazyn1997** [littletomatodonkey/AlexNet-Prod#8]
![image](https://user-images.githubusercontent.com/34644177/135446705-0221696e-d342-4367-a372-1e6ca66c4daa.png)

目前这个方法不会把比对结果写入文件，只是生成这样一个空文件，查看源码发现 print_func 为 print，如果要写入应该如何修改？
![image](https://user-images.githubusercontent.com/34644177/135446979-1d10e28a-6f3f-4783-b5f7-7c0fd65b8c30.png)

**Comment by littletomatodonkey** [comment]
你好，可以重新安装reprod_logger这个whl包，目前已经修复了哈

**Comment by lazyn1997** [comment]
已解决，感谢回复
